version: '2'

services:
  traefik:
    image: traefik:alpine
    ports:
      - 80:80
      - 8080:8080 # WebUIを有効化させる際に必要
      - 443:443
    volumes:
      - .:/etc/traefik/

  
  wordpress:
    image: wordpress
    links:
      - db:mysql

  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: 'rootpassword'
